name: pick_your_poison
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.0
    
  #icons
  flutter_svg: ^2.0.14
  # fonts
  google_fonts: ^6.2.1
  # http
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/cap/
    - assets/cap/texture/black/
    - assets/cap/texture/other/
    - assets/cap/texture/white/
    - assets/stem/
    - assets/stem/texture/dark-bg/
    - assets/stem/texture/light-bg/
    - assets/gills/
    - assets/icons/
    - assets/ring/
    - assets/Species/Amanita_Family/    
    - assets/Species/Bolete_Family/  
    - assets/Species/Chanterelle_Family/  
    - assets/Species/Crepidotus_Family/  
    - assets/Species/Entoloma_Family/  
    - assets/Species/Ink_Cap_Family/      
    - assets/Species/Lepiota_Family/  
    - assets/Species/Mushroom_Family/         
    - assets/Species/Paxillus_Family/  
    - assets/Species/Russula_Family/     
    - assets/Species/Stropharia_Family/  
    - assets/Species/Wax_Gill_Family/
    - assets/Species/Bolbitius_Family/  
    - assets/Species/Bracket_Fungi/  
    - assets/Species/Cortinarius_Family/  
    - assets/Species/Ear-Pick_Family/    
    - assets/Species/Hydnum_Family/    
    - assets/Species/Jelly_Discs_Family/  
    - assets/Species/Morel_Family/    
    - assets/Species/Oyster_Mushroom_Family/  
    - assets/Species/Pluteus_Family/   
    - assets/Species/Saddle-Cup_Family/  
    - assets/Species/Tricholoma_Family/
    - assets/tutorial/
